version: '3.8'

services:
  patient:
    build: ./netflix
    container_name: patient_netflix
    ports:
      - "5000:5000"
    restart: unless-stopped
    networks:
      - sentinel_net

  nginx:
    image: nginx:alpine
    container_name: sentinel_nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/nginx_dynamic.conf:/etc/nginx/conf.d/dynamic.conf:rw
    depends_on:
      - patient
    restart: unless-stopped
    networks:
      - sentinel_net

  dashboard:
    build: ./dashboard
    container_name: sentinel_dashboard
    ports:
      - "8080:8080"
    depends_on:
      - patient
    networks:
      - sentinel_net

  healer:
    build: ./healer
    container_name: sentinel_healer
    depends_on:
      - dashboard
      - patient
      - nginx
    volumes:
      - //var/run/docker.sock:/var/run/docker.sock
      - ./nginx:/etc/sentinel_nginx
    networks:
      - sentinel_net

networks:
  sentinel_net:
    driver: bridge
